//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConscienceLoan.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ConscienceLoanEntities : DbContext
    {
        public ConscienceLoanEntities()
            : base("name=ConscienceLoanEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BankCard> BankCard { get; set; }
        public virtual DbSet<InvestmentRecord> InvestmentRecord { get; set; }
        public virtual DbSet<Tender> Tender { get; set; }
        public virtual DbSet<UserInfo> UserInfo { get; set; }
        public virtual DbSet<FinancialRecords> FinancialRecords { get; set; }
        public virtual DbSet<FinancialRecordsHistory> FinancialRecordsHistories { get; set; }
    
        public virtual ObjectResult<FinancialRecordsHistory> RecordsHistory(Nullable<int> type)
        {
            var typeParameter = type.HasValue ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FinancialRecordsHistory>("RecordsHistory", typeParameter);
        }
    
        public virtual ObjectResult<FinancialRecordsHistory> RecordsHistory(Nullable<int> type, MergeOption mergeOption)
        {
            var typeParameter = type.HasValue ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FinancialRecordsHistory>("RecordsHistory", mergeOption, typeParameter);
        }
    }
}
