//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConscienceLoan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tender
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tender()
        {
            this.InvestmentRecord = new HashSet<InvestmentRecord>();
        }
    
        public int TenID { get; set; }
        public string TenTitle { get; set; }
        public string TenContent { get; set; }
        public int TenLumpSum { get; set; }
        public int TenTheterm { get; set; }
        public double TenMonthRateOfReturn { get; set; }
        public string TenPromise { get; set; }
        public double TenMinInvestment { get; set; }
        public string TenStartTime { get; set; }
        public string TenEndTime { get; set; }
        public string TenTenderType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvestmentRecord> InvestmentRecord { get; set; }
    }
}
